# Generated by Django 4.0 on 2021-12-28 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Drivers',
            new_name='Driver',
        ),
    ]
